# -*- coding: utf-8 -*-
"""veiculo atualizado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/guilherme13022002/vehicle/blob/main/veiculo%20atualizado.ipynb
"""

import pandas as pd
url = "real-world-fuel-efficiency-1.csv"
df = pd.read_csv(url, skiprows = 0, skipfooter = 0, header=0, sep = ',')
df.head()

df



import pandas as pd
import matplotlib.pyplot as plt
url = "real-world-fuel-efficiency-1.csv"



df=pd.read_csv(url)
df.info()

df.describe()

df5 = df[['Hybrid/Non-Hybrid', 'ESTIMATED FUEL COSTS PER GALLON']]
df5

veichle = df5['Hybrid/Non-Hybrid']=='Non-Hybrid'

veichle.sum()

df6 = df5[veichle]

df6

hybrid = df5['Hybrid/Non-Hybrid']!='Non-Hybrid'

df7 =df5[hybrid]

df7.describe()

df7.sum()

df6= df6['ESTIMATED FUEL COSTS PER GALLON'].str.replace('$', '')

df6

df6= df6['ESTIMATED FUEL COSTS PER GALLON'].str.replace('$', '').astype(float)